//JavaScript
var chart = new FamilyTree(document.getElementById("tree"), {
    mouseScrool: FamilyTree.none,
    siblingSeparation: 120,
    template: "john",
    nodeBinding: {
      field_0: "name",
      field_1: "title",
      img_0: "img",
    },
  });
  
  chart.load([
    {
      id: 1,
      name: "OLARERIN",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 2,
      fid: 1,
      name: "OSUNTOLA",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 3,
      fid: 1,
      name: "FAJEMIROKUN",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 4,
      fid: 1,
      name: "FAJEMISONU",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 5,
      mid: 3,
      name: "NIKITI",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 6,
      mid: 3,
      name: "JALA 1",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 7,
      mid: 3,
      name: "JALA 2",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 8,
      mid: 3,
      name: "FATUYOLE",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 9,
      mid: 3,
      name: "SADIYA",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 10,
      mid: 3,
      name: "ESUBAMBI",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 11,
      mid: 3,
      name: "BOSEDE",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 12,
      mid: 3,
      name: "JALA 3",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 13,
      mid: 3,
      name: "OSUNSANYA",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 14,
      mid: 3,
      name: "AWOSEYIN",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 15,
      mid: 3,
      name: "ADEYENWO",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 16,
      mid: 3,
      name: "FAWEKOMI",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 17,
      mid: 3,
      name: "DEMOLA",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 18,
      mid: 3,
      name: "OSUNWE",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 19,
      mid: 3,
      name: "OGUNDIPE",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 20,
      mid: 3,
      name: "MALAO",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 21,
      mid: 3,
      name: "ABAYOMI",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 22,
      mid: 3,
      name: "OGUNSOLA",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 23,
      mid: 3,
      name: "ADESU",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 24,
      mid: 3,
      name: "ARODO",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 25,
      mid: 3,
      name: "OMOTOLA",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 26,
      mid: 3,
      name: "OLAMGOKE",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 27,
      mid: 3,
      name: "FANURE",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 28,
      mid: 3,
      name: "MOLORE",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 29,
      mid: 3,
      name: "FAWUSA",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 30,
      mid: 3,
      name: "OLAMTOKE",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 31,
      mid: 5,
      name: "AKINSANYA",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 32,
      mid: 5,
      name: "SANEI",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 33,
      mid: 6,
      name: "IJIFOLAWE",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 34,
      mid: 6,
      name: "AJAYI",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 35,
      mid: 7,
      name: "MEWOLA",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 36,
      mid: 8,
      name: "ELUFOYO",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 37,
      mid: 8,
      name: "GBAGBE",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 38,
      mid: 8,
      name: "PONDUN",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 39,
      mid: 8,
      name: "ODUDEYI",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 40,
      mid: 8,
      name: "OSUNDALU",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 41,
      mid: 9,
      name: "SAYONU",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 42,
      mid: 9,
      name: "FATIKIMI",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 43,
      mid: 9,
      name: "IFAROOMO",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 44,
      mid: 10,
      name: "AKINTUNDE",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 45,
      mid: 10,
      name: "AKINSANYA",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 46,
      mid: 11,
      name: "WANDE",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 47,
      mid: 11,
      name: "IGE",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 48,
      mid: 12,
      name: "OSUNDOREPO",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 49,
      mid: 12,
      name: "ONIKI",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 50,
      mid: 13,
      name: "FOLAJIMI",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 51,
      mid: 13,
      name: "AKINGBOLA",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 52,
      mid: 13,
      name: "YELOLA",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 53,
      mid: 15,
      name: "ADERONKE",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 54,
      mid: 15,
      name: "TIDOYE",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 55,
      mid: 16,
      name: "FUNMILADE",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 56,
      mid: 16,
      name: "SALU",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 57,
      mid: 16,
      name: "FAYEMI",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 58,
      mid: 16,
      name: "E.IJIGBOLA",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 59,
      mid: 16,
      name: "S.LAGUNDOYE",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 60,
      mid: 17,
      name: "FAMAKINWA",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 61,
      mid: 17,
      name: "OLOSUNDE",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 62,
      mid: 17,
      name: "ADEOTI",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 63,
      mid: 18,
      name: "GBEYIDE",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 64,
      mid: 18,
      name: "FORE",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 65,
      mid: 19,
      name: "FASULE",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 66,
      mid: 19,
      name: "ODEWUMI",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 67,
      mid: 20,
      name: "BIMPE",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 68,
      mid: 21,
      name: "IJIWARE",
      img: "https://www.svgrepo.com/show/382099/female-avatar-girl-face-woman-user-2.svg",
      gender: "female",
    },
    {
      id: 69,
      mid: 21,
      name: "JOHN TOGUN",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 70,
      mid: 24,
      name: "AKINTOKUN",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 71,
      mid: 25,
      name: "OSUNGBOHUN",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 72,
      mid: 28,
      name: "J. OSUNROGBA",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 73,
      mid: 28,
      name: "ILELOMIA",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
    {
      id: 74,
      mid: 28,
      name: "TAIYEWO",
      img: "https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png",
      gender: "male",
    },
  ]);